// 这个文件集中提供客户画像、营销活动和自动跟进的演示数据，供语音机器人客户运营页面复用。
import {
  CustomerProfile,
  FollowUpRule,
  FollowUpTask,
  MarketingCampaign,
  MarketingTriggerTiming,
} from '../../types';

const day = 24 * 60 * 60 * 1000;
const now = new Date('2026-05-25T10:00:00+08:00').getTime();

export const CAMPAIGN_GOAL_LABELS: Record<string, string> = {
  conversion: '转化',
  renewal: '续费',
  reactivation: '唤醒',
  care: '关怀',
  follow_up: '回访',
};

export const MARKETING_TRIGGER_LABELS: Record<MarketingTriggerTiming, string> = {
  post_resolution: '业务办理完成后',
  price_inquiry: '用户主动问价格/优惠时',
  interest_detected: '用户表达兴趣时',
  hesitation: '用户犹豫时',
  pre_hangup: '通话结束前',
};

export const FOLLOW_UP_STATUS_LABELS: Record<string, string> = {
  pending: '待执行',
  running: '执行中',
  connected: '已接通',
  no_answer: '未接通',
  completed: '已完成',
  rejected: '已拒绝',
  cancelled: '已取消',
  failed: '已失败',
  transferred: '已转人工',
  expired: '已过期',
};

export const FOLLOW_UP_TRIGGER_LABELS: Record<string, string> = {
  later_contact: '用户表达稍后联系',
  explicit_time: '用户说出明确时间',
  considering: '用户表示考虑一下',
  appointment_success: '用户预约成功',
  no_answer: '用户未接通',
  post_call_review: '通话结束后需要回访',
};

export const MOCK_CUSTOMER_PROFILES: CustomerProfile[] = [
  {
    id: 'cust_1',
    name: '张伟',
    phoneNumber: '13800138000',
    region: '上海',
    customerLevel: '高价值客户',
    marketingStatus: '可推荐',
    followUpStatus: '待跟进',
    riskStatus: '正常',
    lastCallResult: '有意向',
    tags: ['高净值', '价格敏感', '需要回访'],
    structuredTags: [
      { id: 'tag_1', name: '高净值', type: 'basic', source: 'manual', confidence: 'high', updatedAt: now - 12 * day, explanation: '人工根据历史消费金额标记为高价值客户。' },
      { id: 'tag_2', name: '价格敏感', type: 'intent', source: 'call_recognition', confidence: 'high', updatedAt: now - 2 * day, expiresAt: now + 28 * day, explanation: '最近通话中多次询问优惠和折扣。' },
      { id: 'tag_3', name: '需要回访', type: 'result', source: 'follow_up_result', confidence: 'high', updatedAt: now - day, expiresAt: now + 6 * day, explanation: '用户说“下周再联系我”。' },
    ],
    recommendedCampaignIds: ['camp_renewal_offer'],
    touchBlockReasons: [],
    lastInteraction: now - day,
    notes: '客户对优惠比较敏感，适合在业务结束后用服务优先方式推荐续费优惠；已约定下周二上午再次联系。',
    interactions: [
      { id: 'i1', type: 'call', time: now - day, title: '价格咨询通话', detail: '咨询续费价格，表达“有点贵，下周再联系”。', result: '有意向', botName: '滴滴出行智能客服 (Demo)', flowName: '产品咨询 Flow' },
      { id: 'i2', type: 'marketing', time: now - day + 5 * 60 * 1000, title: '推荐老客户续费优惠', detail: '用户表示愿意之后再了解。', result: '感兴趣' },
      { id: 'i3', type: 'follow_up', time: now + 6 * day, title: '自动跟进任务已生成', detail: '计划下周二上午自动外呼。', result: '待执行' },
    ],
  },
  {
    id: 'cust_2',
    name: '李娜',
    phoneNumber: '13912345678',
    region: '北京',
    customerLevel: 'VIP客户',
    marketingStatus: '禁止触达',
    followUpStatus: '无跟进',
    riskStatus: '投诉风险',
    lastCallResult: '转人工',
    tags: ['VIP', '投诉风险', '拒绝营销'],
    structuredTags: [
      { id: 'tag_4', name: 'VIP', type: 'basic', source: 'manual', confidence: 'high', updatedAt: now - 30 * day, explanation: '客户等级为 VIP。' },
      { id: 'tag_5', name: '投诉风险', type: 'risk', source: 'call_recognition', confidence: 'high', updatedAt: now - 2 * day, expiresAt: now + 14 * day, explanation: '最近通话存在物流延误投诉和明显负面情绪。' },
      { id: 'tag_6', name: '拒绝营销', type: 'risk', source: 'marketing_result', confidence: 'high', updatedAt: now - 3 * day, expiresAt: now + 27 * day, explanation: '用户明确表示近期不要再推荐活动。' },
    ],
    recommendedCampaignIds: [],
    touchBlockReasons: ['投诉风险客户禁止触达', '用户处于拒绝营销冷却期'],
    lastInteraction: now - 2 * day,
    notes: '近期多次投诉，当前只适合服务和安抚，不适合任何营销推荐。',
    interactions: [
      { id: 'i4', type: 'call', time: now - 2 * day, title: '售后投诉通话', detail: '物流延误投诉，已转人工处理。', result: '转人工', botName: '售后服务机器人', flowName: '投诉受理 Flow' },
      { id: 'i5', type: 'manual', time: now - 2 * day + 600000, title: '人工标记触达限制', detail: '坐席标记 30 天内不做营销触达。', result: '禁止触达' },
    ],
  },
  {
    id: 'cust_3',
    name: '王强',
    phoneNumber: '15098765432',
    region: '深圳',
    customerLevel: '普通客户',
    marketingStatus: '冷却中',
    followUpStatus: '跟进中',
    riskStatus: '正常',
    lastCallResult: '未接通',
    tags: ['沉睡用户', '促销激活', '多次未接'],
    structuredTags: [
      { id: 'tag_7', name: '沉睡用户', type: 'behavior', source: 'call_recognition', confidence: 'medium', updatedAt: now - 20 * day, explanation: '超过 90 天无主动进线。' },
      { id: 'tag_8', name: '多次未接', type: 'behavior', source: 'follow_up_result', confidence: 'high', updatedAt: now - 4 * day, expiresAt: now + 10 * day, explanation: '最近两次自动跟进均未接通。' },
    ],
    recommendedCampaignIds: ['camp_reactivate'],
    touchBlockReasons: ['今天已触达 1 次，进入频控保护'],
    lastInteraction: now - 4 * day,
    notes: '沉睡客户，适合低频唤醒，不建议一天内重复拨打。',
    interactions: [
      { id: 'i6', type: 'follow_up', time: now - 4 * day, title: '沉睡唤醒外呼', detail: '首次外呼未接通。', result: '未接通', botName: '唤醒回访机器人', flowName: '沉睡唤醒 Flow' },
      { id: 'i7', type: 'follow_up', time: now - 3 * day, title: '重试外呼', detail: '第二次外呼仍未接通。', result: '未接通' },
    ],
  },
  {
    id: 'cust_4',
    name: '赵敏',
    phoneNumber: '18655556666',
    region: '杭州',
    customerLevel: '企业客户',
    marketingStatus: '已触达',
    followUpStatus: '已完成',
    riskStatus: '正常',
    lastCallResult: '已解决',
    tags: ['企业客户', '高频', '已预约'],
    structuredTags: [
      { id: 'tag_9', name: '企业客户', type: 'basic', source: 'manual', confidence: 'high', updatedAt: now - 60 * day, explanation: '企业采购负责人。' },
      { id: 'tag_10', name: '已预约', type: 'result', source: 'follow_up_result', confidence: 'high', updatedAt: now - day, explanation: '已完成产品演示预约。' },
    ],
    recommendedCampaignIds: ['camp_enterprise_care'],
    touchBlockReasons: [],
    lastInteraction: now - day,
    notes: '企业采购负责人，偏好周一上午沟通，已完成预约提醒。',
    interactions: [
      { id: 'i8', type: 'call', time: now - 2 * day, title: '企业服务咨询', detail: '确认团队版服务方案。', result: '已预约', botName: '企业客服机器人', flowName: '企业咨询 Flow' },
      { id: 'i9', type: 'follow_up', time: now - day, title: '预约提醒', detail: '自动外呼提醒产品演示时间。', result: '已完成' },
    ],
  },
];

export const MOCK_MARKETING_CAMPAIGNS: MarketingCampaign[] = [
  {
    id: 'camp_renewal_offer',
    name: '老客户续费优惠推荐',
    status: 'active',
    goal: 'renewal',
    priority: 1,
    targetRegions: ['上海', '杭州'],
    targetTags: ['价格敏感', '高净值'],
    excludeTags: ['拒绝营销', '投诉风险', '黑名单'],
    targetLastCallResults: ['有意向', '已解决'],
    requireNoRecentTouch: true,
    requireFollowUpTask: false,
    excludeRiskTags: ['投诉风险', '情绪异常'],
    startDate: '2026-05-01',
    endDate: '2026-06-30',
    speechContent: '您是老客户，目前有一档续费优惠，价格会比标准方案更划算，需要我简单介绍一下吗？',
    speechVariants: [
      { id: 'v1', label: '价格敏感客户', matchTags: ['价格敏感'], content: '您刚才提到比较关注价格，目前老客户有一档优惠方案，我可以简单给您说明一下。' },
      { id: 'v2', label: '高价值客户', matchTags: ['高净值'], content: '您当前符合专属客户权益，可以优先了解续费优惠方案。' },
    ],
    interestedReply: '好的，我先用一分钟给您说明重点权益。',
    rejectedReply: '好的，后续不打扰您，我们先继续处理当前问题。',
    triggerTimings: ['post_resolution', 'price_inquiry', 'hesitation'],
    executableBotIds: ['bot_didi_demo'],
    executableFlowIds: ['main'],
    requireUserConfirmation: true,
    allowAutoFollowUp: true,
    smsTemplateId: 'SMS_RENEWAL_01',
    exposureCount: 1260,
    conversionCount: 146,
    stats: { exposureCount: 1260, interestedCount: 438, rejectedCount: 180, transferCount: 52, conversionCount: 146, negativeFeedbackCount: 8 },
    updatedAt: now - day,
  },
  {
    id: 'camp_reactivate',
    name: '沉睡客户温和唤醒',
    status: 'active',
    goal: 'reactivation',
    priority: 3,
    targetRegions: [],
    targetTags: ['沉睡用户'],
    excludeTags: ['黑名单', '拒绝营销', '投诉风险'],
    targetLastCallResults: ['未接通', '拒绝'],
    requireNoRecentTouch: true,
    requireFollowUpTask: true,
    excludeRiskTags: ['投诉风险'],
    startDate: '2026-05-10',
    endDate: '2026-08-31',
    speechContent: '您好，看到您有段时间没有使用服务了，我们这边有一个老用户回归权益，想简单和您确认是否需要保留。',
    speechVariants: [
      { id: 'v3', label: '多次未接客户', matchTags: ['多次未接'], content: '您好，这次只占用您几十秒，主要确认是否继续为您保留老用户权益。' },
    ],
    interestedReply: '好的，我帮您继续保留权益，并说明一下使用方式。',
    rejectedReply: '好的，已记录您的意愿，近期不会再重复提醒。',
    triggerTimings: ['pre_hangup'],
    executableBotIds: ['bot_didi_demo'],
    executableFlowIds: ['lookup'],
    requireUserConfirmation: true,
    allowAutoFollowUp: false,
    exposureCount: 840,
    conversionCount: 64,
    stats: { exposureCount: 840, interestedCount: 168, rejectedCount: 210, transferCount: 18, conversionCount: 64, negativeFeedbackCount: 16 },
    updatedAt: now - 2 * day,
  },
  {
    id: 'camp_enterprise_care',
    name: '企业客户服务关怀',
    status: 'scheduled',
    goal: 'care',
    priority: 2,
    targetRegions: ['杭州', '上海'],
    targetTags: ['企业客户'],
    excludeTags: ['投诉风险', '黑名单'],
    targetLastCallResults: ['已解决', '有意向'],
    requireNoRecentTouch: false,
    requireFollowUpTask: false,
    excludeRiskTags: ['黑名单'],
    startDate: '2026-06-01',
    endDate: '2026-07-15',
    speechContent: '我们会为企业客户提供一次服务使用回访，确认您团队近期使用是否顺畅。',
    interestedReply: '好的，我帮您记录反馈，并安排客户经理继续跟进。',
    rejectedReply: '好的，感谢您的反馈，后续如需支持可以随时联系我们。',
    triggerTimings: ['post_resolution'],
    executableBotIds: ['bot_didi_demo'],
    executableFlowIds: ['verification'],
    requireUserConfirmation: false,
    allowAutoFollowUp: true,
    exposureCount: 320,
    conversionCount: 42,
    stats: { exposureCount: 320, interestedCount: 128, rejectedCount: 34, transferCount: 20, conversionCount: 42, negativeFeedbackCount: 2 },
    updatedAt: now - 3 * day,
  },
];

export const MOCK_FOLLOW_UP_RULES: FollowUpRule[] = [
  {
    id: 'rule_later_contact',
    name: '稍后联系自动外呼',
    enabled: true,
    applicableBotIds: ['bot_didi_demo'],
    applicableFlowIds: ['main', 'lookup'],
    botNames: ['滴滴出行智能客服 (Demo)'],
    flowNames: ['主入口 Flow', '订单查询 Flow'],
    triggers: ['later_contact', 'explicit_time', 'considering'],
    useUserSpecifiedTime: true,
    defaultDelayDays: 3,
    preferredTimeRange: '09:30-18:30',
    actions: ['auto_call', 'write_tag', 'enter_flow'],
    executionBotId: 'bot_didi_demo',
    executionFlowId: 'lookup',
    retryPolicy: { maxRetries: 3, retryIntervalHours: 24, maxDailyAttempts: 1, failureAction: 'delay' },
    touchProtection: { maxDailyCalls: 1, maxWeeklyCalls: 3, avoidNightCalls: true, avoidHolidays: true, rejectCooldownDays: 14, blockComplaintRisk: true, blockBlacklist: true },
    exitConditions: ['已完成', '已拒绝', '已人工接管', '达到最大重试次数', '任务过期'],
  },
  {
    id: 'rule_post_call_review',
    name: '通话结束满意度回访',
    enabled: true,
    applicableBotIds: ['bot_didi_demo'],
    applicableFlowIds: ['verification'],
    botNames: ['滴滴出行智能客服 (Demo)'],
    flowNames: ['身份验证 Flow'],
    triggers: ['post_call_review', 'appointment_success'],
    useUserSpecifiedTime: false,
    defaultDelayDays: 2,
    preferredTimeRange: '10:00-17:00',
    actions: ['auto_call', 'manual_task'],
    executionBotId: 'bot_didi_demo',
    executionFlowId: 'verification',
    retryPolicy: { maxRetries: 2, retryIntervalHours: 12, maxDailyAttempts: 1, failureAction: 'transfer' },
    touchProtection: { maxDailyCalls: 1, maxWeeklyCalls: 2, avoidNightCalls: true, avoidHolidays: false, rejectCooldownDays: 30, blockComplaintRisk: false, blockBlacklist: true },
    exitConditions: ['已完成', '已拒绝', '已人工接管'],
  },
];

export const MOCK_FOLLOW_UP_TASKS: FollowUpTask[] = [
  {
    id: 'fu_1001',
    customerName: '张伟',
    phoneNumber: '13800138000',
    sourceCallId: 'CALL-20260518-001',
    sourceBotName: '滴滴出行智能客服 (Demo)',
    sourceFlowName: '产品咨询 Flow',
    reason: '用户表达“下周再联系我”，需要按约定再次外呼。',
    plannedCallTime: now + 6 * day,
    executionBotName: '滴滴出行智能客服 (Demo)',
    executionFlowName: '订单查询 Flow',
    status: 'pending',
    retryCount: 0,
    latestResult: '等待到期执行',
    ruleId: 'rule_later_contact',
    attempts: [],
  },
  {
    id: 'fu_1002',
    customerName: '王强',
    phoneNumber: '15098765432',
    sourceCallId: 'CALL-20260520-009',
    sourceBotName: '唤醒回访机器人',
    sourceFlowName: '沉睡唤醒 Flow',
    reason: '沉睡用户唤醒首次未接通，进入重试策略。',
    plannedCallTime: now + day,
    executionBotName: '唤醒回访机器人',
    executionFlowName: '沉睡唤醒 Flow',
    status: 'no_answer',
    retryCount: 2,
    latestResult: '最近一次未接通，24 小时后重试',
    ruleId: 'rule_later_contact',
    attempts: [
      { id: 'a1', taskId: 'fu_1002', executedAt: now - 3 * day, result: 'no_answer', summary: '首次外呼未接通。' },
      { id: 'a2', taskId: 'fu_1002', executedAt: now - 2 * day, result: 'no_answer', summary: '第二次外呼仍未接通。' },
    ],
  },
  {
    id: 'fu_1003',
    customerName: '赵敏',
    phoneNumber: '18655556666',
    sourceCallId: 'CALL-20260523-118',
    sourceBotName: '企业客服机器人',
    sourceFlowName: '企业咨询 Flow',
    reason: '预约成功后自动提醒产品演示时间。',
    plannedCallTime: now - day,
    executionBotName: '企业客服机器人',
    executionFlowName: '预约提醒 Flow',
    status: 'completed',
    retryCount: 1,
    latestResult: '已接通并完成提醒',
    ruleId: 'rule_post_call_review',
    attempts: [
      { id: 'a3', taskId: 'fu_1003', executedAt: now - day, result: 'connected', summary: '用户确认会按时参加演示。' },
    ],
  },
  {
    id: 'fu_1004',
    customerName: '周明',
    phoneNumber: '17788889999',
    sourceCallId: 'CALL-20260524-220',
    sourceBotName: '售后服务机器人',
    sourceFlowName: '售后回访 Flow',
    reason: '售后工单关闭后进行满意度回访。',
    plannedCallTime: now + 2 * day,
    executionBotName: '售后服务机器人',
    executionFlowName: '满意度回访 Flow',
    status: 'transferred',
    retryCount: 1,
    latestResult: '用户要求人工继续处理，已转人工',
    ruleId: 'rule_post_call_review',
    attempts: [
      { id: 'a4', taskId: 'fu_1004', executedAt: now - 4 * 60 * 60 * 1000, result: 'transferred', summary: '用户对处理结果仍有疑问，转人工。' },
    ],
  },
];

export function getCampaignTagNames(campaign: MarketingCampaign) {
  return [...campaign.targetTags, ...(campaign.excludeTags || [])];
}

export function formatDateTime(value: number) {
  return new Date(value).toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' });
}
